### ISSUE TITLE
any updates on using libsodium mshild 

### ISSUE THREAD

**Issue by jorgeelmundoso** [stouset/secrets#80] opened 2020-04-16 19:59 UTC
FWIW, `libsodium` recently added an [`mshield`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/utils.c#L738) function that performs in-memory encryption. When that is stabilized and released, I'll be able to use it.

Of course, anyone with similar privileges can still find the key and IV in memory and decrypt the secret, but it does increase the level of effort for such an attach.

_Originally posted by @stouset in https://github.com/stouset/secrets/issues/72#issuecomment-520934478_

That was the result of an other issue from last year, is that still on the roaster?

**Comment by stouset** [comment] 2020-04-16 21:23
There haven't been [any new releases](https://github.com/jedisct1/libsodium/releases) since then. Once it's added, I'll be happy to write the code to take advantage of it.

**Comment by stouset** [comment] 2020-04-16 21:24
Closed this ticket since it's a dupe of #73.

**Closed by stouset** 2020-04-16 21:23 UTC

**Comment by jorgeelmundoso** [comment] 2020-04-16 21:25
thanks
